language: node_js
node_js:
- "0.12.2"
before_script:
  - gem install sass
  - npm install -g gulp
  - npm install -g grunt-cli
  - npm install -g bower
script: bash ./deploy.sh
on:
  condition: "$TRAVIS_PULL_REQUEST" == "false"
env:
  global:
    - GH_REF: github.com/Esri/calcite-bootstrap.git
    - secure: "GmgGsfJug/oHxDxabSwt+i5cs5PlLvUMTST5NFVrHbitMz1RUVG+K9XqRT1WAhaXQbnyg+n16NW9tJnSlAuodyYdkM2wL2leoTKFVrD+iDfMXtsr3Vbwlo3Jy7rWaeWombNILidFdP10zUjiHpcmEFjHK5kMCdN+TrWmsrzaqZaN+YTifsNXIvcnJ9NVmVz7hJ+7TEmPwczOnSxypMb9LJvi1zCj48O/Dd5tAUIxWNKyDVvwe+HBmYhvumFqGUWYIrBNCvt9FWaDfoBMcIJ//Q6pBXAKfT4ro8X6YwyJ9LZZguOO/fORaCgWxmCWiBoqJv9jgFfhl/4a76zty4bkhYg5kxkOT2hRcY5dkrmgKgACsaUpz/DhsHAZl4jkr7E0HwoXyww6e664/oU3IONPH8BKIPJdBlC82vUd867RAM1WcLAM3lhFOkJjVfuF2AjjHfZQcuCqu7xu+i8eo8O0OrmkQ2wEcbC18WLtH4w18285YmWnNmoUk4rlEA7PVhFcrN2wlITlZ5Yp1PhpTiANU63QHsrJyeN87q+B/y4HWmn1F4nneXSun+/RMzH+DDl5FR3lvMNJ746/9QPCEnqXQVZNi4k41l6yBc/jZ9lHYd/g39wWFN4PDFYN9V4D8xyiSO9Wn9p2p8xALMlwJH30F+KAo2xtQBtH5VhtBrbYg8g="
